
name: CI with install

on:
  pull_request:
    branches:
      - develop
      - main
    paths-ignore:
      - 'docs/**'
      - '.gitignore'
      - '*.md'
      - 'CITATION.cff'
      - 'LICENSE.txt'
      - 'readthedocs.yml'

jobs:
  testing:
    runs-on: ubuntu-latest
    container:
      image: continuumio/miniconda3:4.12.0
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: install package
        run: |
          pip install .[tests]

      - name: Run tests
        run: |
          pytest tests

      - name: Run examples
        run: |
          cd examples
          python balanced_scenario.py
          python under_produce_scenario.py
          python over_produce_scenario.py
          python icf_example.py
